#!/bin/bash

for netdev in $(cat /proc/net/dev | grep : | awk -F ":" '{ print $1 }' | grep -v lo)  
do
  echo Change MAC of device: $netdev
  echo
  sudo ip link set dev $netdev down
  sleep 0.2
  sudo macchanger -r $netdev
  sleep 0.2
  sudo ip link set dev $netdev up
  echo
done
