#!/bin/bash

# Check whether the script is carried out with root rights
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Loop via network devices
while IFS= read -r netdev; do
  echo "Changing MAC of device: $netdev"
  echo
  
  # Shut down device
  if ! su -x ip link set dev "$netdev" down; then
    echo "Failed to bring down $netdev. Skipping..."
    continue
  fi
  sleep 0.2
  
  # Change MAC-Adresse
  if ! su -x macchanger -r "$netdev"; then
    echo "Failed to change MAC for $netdev. Skipping..."
    continue
  fi
  sleep 0.2
  
  # Restart device
  if ! su -x ip link set dev "$netdev" up; then
    echo "Failed to bring up $netdev. Skipping..."
    continue
  fi
  echo
done < <(grep : /proc/net/dev | awk -F ":" '{ print $1 }' | grep -v lo)
